### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jakee246/project8#1]
One of the few projects I haven't been able to immediately break! While it does work though, I do see some inconsistent indentation in `app.rb` and `index.erb` that I'd like you to fix. The [resources on this page](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) should be helpful here.

Let me know if you encounter any difficulties with that and I'll be happy to hop on a screenshare!

**Comment by chrisvfritz** [comment]
I'm still seeing a lot of inconsistent indentation. If you look at the files on GitHub, you'll see what I mean. [This additional video](https://www.youtube.com/watch?v=GMf8dlrEbB4) should have some tips to help you fix current files. Let me know how it goes!

**Comment by jakee246** [comment]
I changed the settings in my Sublime to show the line indentation. To me
from the examples what I am doing looks correct.

thank you, Jake.

**Comment by chrisvfritz** [comment]
Hi Jake - I'm still seeing the inconsistent indentation here. Pull me over in the next class and I'll be happy to help you recognize and fix these, so that we can approve this project.

**Comment by jakee246** [comment]
See you Monday!

**Comment by jakee246** [comment]
Fixed.

**Comment by chrisvfritz** [comment]
:+1: Looks good!
